"""empty message

Revision ID: 80247c0fdece
Revises: 8ddf964eb0ae
Create Date: 2022-11-04 19:34:09.089702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80247c0fdece'
down_revision = '8ddf964eb0ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks_in_playlists', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tracks_in_playlists', sa.Column('youtube_id', sa.String(length=64), nullable=False))
    op.drop_column('tracks_in_playlists', 'name')
    op.drop_column('tracks_in_playlists', 'track_youtube_id')
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('users', 'username')
    op.add_column('tracks_in_playlists', sa.Column('track_youtube_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tracks_in_playlists', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tracks_in_playlists', 'youtube_id')
    op.drop_column('tracks_in_playlists', 'title')
    # ### end Alembic commands ###
